/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// src/main.ts
__export(exports, {
  SchulteTableSidebarView: () => SchulteTableSidebarView,
  default: () => SchulteTablePlugin
});
var import_obsidian2 = __toModule(require("obsidian"));

// src/view/schulteTableView.ts
var SchulteTableView = class {
  constructor(container, options) {
    this.cells = [];
    this.items = [];
    this.currentIndex = 0;
    this.timerInterval = null;
    this.startTime = 0;
    this.elapsedTime = 0;
    this.isRunning = false;
    this.records = [];
    this.container = container;
    this.options = options;
    this.loadRecords();
    this.createUI();
    this.initTable();
    this.displayRecords();
  }
  loadRecords(storageKey = "schulte-table-records") {
    try {
      const savedRecords = localStorage.getItem(storageKey);
      if (savedRecords) {
        this.records = JSON.parse(savedRecords);
      }
    } catch (e) {
      console.error("Failed to load records:", e);
      this.records = [];
    }
  }
  saveRecords(storageKey) {
    try {
      localStorage.setItem(storageKey, JSON.stringify(this.records));
    } catch (e) {
      console.error("Failed to save records:", e);
    }
  }
  addRecord(time) {
    const newRecord = {
      date: Date.now(),
      time,
      size: this.options.size * this.options.size,
      type: "schulte-table",
      gameType: "\u8212\u5C14\u7279\u8868\u683C",
      metadata: `${this.options.size}x${this.options.size}`
    };
    this.records.unshift(newRecord);
    if (this.records.length > 10) {
      this.records = this.records.slice(0, 10);
    }
    this.saveRecords("schulte-table-records");
    this.displayRecords();
  }
  displayRecords() {
    if (!this.recordsContainer)
      return;
    this.recordsContainer.empty();
    const header = document.createElement("h3");
    header.setText("\u6700\u8FD1\u5B8C\u6210\u8BB0\u5F55");
    this.recordsContainer.appendChild(header);
    if (this.records.length === 0) {
      const noRecords = document.createElement("div");
      noRecords.setText("\u6682\u65E0\u8BB0\u5F55");
      noRecords.addClass("schulte-no-records");
      this.recordsContainer.appendChild(noRecords);
      return;
    }
    const recordsList = document.createElement("div");
    recordsList.addClass("schulte-records-list");
    const recordsToShow = this.records.slice(0, 5);
    recordsToShow.forEach((record, index) => {
      const recordItem = document.createElement("div");
      recordItem.addClass("schulte-record-item");
      const dateStr = new Date(record.date).toLocaleString();
      recordItem.innerHTML = `
        <span class="record-index">${index + 1}.</span>
        <span class="record-size">${record.metadata || record.size}</span>
        <span class="record-type">${record.gameType || this.getTypeDisplayName(record.type)}</span>
        <span class="record-time">${record.time.toFixed(1)}\u79D2</span>
        <span class="record-date">${dateStr}</span>
      `;
      recordsList.appendChild(recordItem);
    });
    this.recordsContainer.appendChild(recordsList);
  }
  getTypeDisplayName(type) {
    switch (type) {
      case "numbers":
        return "\u6570\u5B57";
      case "letters":
        return "\u5B57\u6BCD";
      case "chinese":
        return "\u6C49\u5B57";
      default:
        return type;
    }
  }
  createUI() {
    const wrapper = document.createElement("div");
    wrapper.addClass("schulte-table-container");
    this.container.appendChild(wrapper);
    const controls = document.createElement("div");
    controls.addClass("schulte-controls");
    wrapper.appendChild(controls);
    this.startButton = document.createElement("button");
    this.startButton.setText("\u5F00\u59CB\u8BAD\u7EC3");
    this.startButton.addEventListener("click", () => this.startTraining());
    controls.appendChild(this.startButton);
    this.resetButton = document.createElement("button");
    this.resetButton.setText("\u91CD\u7F6E");
    this.resetButton.addEventListener("click", () => this.resetTable());
    controls.appendChild(this.resetButton);
    this.table = document.createElement("div");
    this.table.addClass("schulte-table");
    this.table.style.setProperty("--grid-size", this.options.size.toString());
    wrapper.appendChild(this.table);
    if (this.options.showTimer) {
      this.timer = document.createElement("div");
      this.timer.addClass("schulte-timer");
      this.timer.setText("\u65F6\u95F4: 0.0\u79D2");
      wrapper.appendChild(this.timer);
    }
    this.stats = document.createElement("div");
    this.stats.addClass("schulte-stats");
    this.stats.setText("\u70B9\u51FB\u5F00\u59CB\u6309\u94AE\u5F00\u59CB\u8BAD\u7EC3");
    wrapper.appendChild(this.stats);
    this.recordsContainer = document.createElement("div");
    this.recordsContainer.addClass("schulte-records");
    wrapper.appendChild(this.recordsContainer);
  }
  initTable() {
    this.generateItems();
    this.table.empty();
    this.cells = [];
    this.table.style.setProperty("--grid-size", this.options.size.toString());
    const gridSize = this.options.size;
    const total = gridSize * gridSize;
    for (let row = 0; row < gridSize; row++) {
      for (let col = 0; col < gridSize; col++) {
        const index = row * gridSize + col;
        if (index >= this.items.length)
          break;
        const cell = document.createElement("div");
        cell.addClass("schulte-cell");
        cell.setText(this.items[index].toString());
        cell.style.gridRow = `${row + 1} / span 1`;
        cell.style.gridColumn = `${col + 1} / span 1`;
        cell.addEventListener("click", () => this.handleCellClick(index));
        this.table.appendChild(cell);
        this.cells.push(cell);
      }
    }
  }
  generateItems() {
    const total = this.options.size * this.options.size;
    this.items = [];
    switch (this.options.type) {
      case "numbers":
        for (let i = 1; i <= total; i++) {
          this.items.push(i);
        }
        break;
      case "letters":
        for (let i = 0; i < total; i++) {
          const charCode = 65 + i % 26;
          this.items.push(String.fromCharCode(charCode));
        }
        break;
      case "chinese":
        const chineseNumbers = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u4E03", "\u516B", "\u4E5D", "\u5341"];
        for (let i = 0; i < total; i++) {
          this.items.push(chineseNumbers[i % chineseNumbers.length]);
        }
        break;
      default:
        for (let i = 1; i <= total; i++) {
          this.items.push(i);
        }
    }
    this.shuffleItems();
  }
  shuffleItems() {
    for (let i = this.items.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [this.items[i], this.items[j]] = [this.items[j], this.items[i]];
    }
  }
  startTraining() {
    if (this.isRunning)
      return;
    this.isRunning = true;
    this.currentIndex = 0;
    this.startButton.setText("\u8BAD\u7EC3\u4E2D...");
    this.startButton.setAttribute("disabled", "true");
    this.cells.forEach((cell) => {
      cell.removeClass("correct");
      cell.removeClass("wrong");
    });
    let targetItems = [];
    switch (this.options.type) {
      case "numbers":
        targetItems = Array.from({ length: this.items.length }, (_, i) => i + 1);
        break;
      case "letters":
        targetItems = Array.from({ length: this.items.length }, (_, i) => {
          const charCode = 65 + i % 26;
          return String.fromCharCode(charCode);
        });
        break;
      case "chinese":
        const chineseNumbers = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u4E03", "\u516B", "\u4E5D", "\u5341"];
        targetItems = Array.from({ length: this.items.length }, (_, i) => {
          return chineseNumbers[i % chineseNumbers.length];
        });
        break;
      default:
        targetItems = Array.from({ length: this.items.length }, (_, i) => i + 1);
    }
    this.updateStats(`\u8BF7\u6309\u987A\u5E8F\u70B9\u51FB: ${targetItems[0]}`);
    this.startTime = Date.now();
    this.elapsedTime = 0;
    if (this.options.showTimer) {
      this.timerInterval = window.setInterval(() => {
        this.elapsedTime = (Date.now() - this.startTime) / 1e3;
        this.timer.setText(`\u65F6\u95F4: ${this.elapsedTime.toFixed(1)}\u79D2`);
        if (this.options.timeLimit > 0 && this.elapsedTime >= this.options.timeLimit) {
          this.endTraining(false);
        }
      }, 100);
    }
  }
  handleCellClick(index) {
    if (!this.isRunning)
      return;
    const targetValue = this.getTargetValue(this.currentIndex);
    const clickedValue = this.items[index];
    if (clickedValue.toString() === targetValue.toString()) {
      this.cells[index].addClass("correct");
      this.currentIndex++;
      if (this.currentIndex >= this.items.length) {
        this.endTraining(true);
        return;
      }
      const nextTarget = this.getTargetValue(this.currentIndex);
      this.updateStats(`\u8BF7\u6309\u987A\u5E8F\u70B9\u51FB: ${nextTarget}`);
    } else {
      this.cells[index].addClass("wrong");
      this.updateStats(`\u9519\u8BEF! \u8BF7\u70B9\u51FB: ${targetValue}`);
      setTimeout(() => {
        this.cells[index].removeClass("wrong");
      }, 500);
    }
  }
  getTargetValue(index) {
    switch (this.options.type) {
      case "numbers":
        return index + 1;
      case "letters":
        const charCode = 65 + index % 26;
        return String.fromCharCode(charCode);
      case "chinese":
        const chineseNumbers = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u4E03", "\u516B", "\u4E5D", "\u5341"];
        return chineseNumbers[index % chineseNumbers.length];
      default:
        return index + 1;
    }
  }
  endTraining(success) {
    this.isRunning = false;
    if (this.timerInterval) {
      clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
    this.startButton.setText("\u5F00\u59CB\u8BAD\u7EC3");
    this.startButton.removeAttribute("disabled");
    if (success) {
      this.updateStats(`\u8BAD\u7EC3\u5B8C\u6210! \u7528\u65F6: ${this.elapsedTime.toFixed(1)}\u79D2`);
      this.addRecord(this.elapsedTime);
    } else {
      this.updateStats(`\u65F6\u95F4\u5230! \u5B8C\u6210\u5EA6: ${this.currentIndex}/${this.items.length}`);
    }
  }
  resetTable() {
    if (this.isRunning) {
      this.endTraining(false);
    }
    this.initTable();
    this.currentIndex = 0;
    this.elapsedTime = 0;
    if (this.options.showTimer) {
      this.timer.setText("\u65F6\u95F4: 0.0\u79D2");
    }
    this.updateStats("\u70B9\u51FB\u5F00\u59CB\u6309\u94AE\u5F00\u59CB\u8BAD\u7EC3");
  }
  updateStats(text) {
    this.stats.setText(text);
  }
};

// src/view/colorWordView.ts
var ColorWordView = class {
  constructor(container, options) {
    this.colorWords = [];
    this.colorWordElements = [];
    this.chineseColors = [
      { name: "\u7EA2\u8272", color: "#e74c3c" },
      { name: "\u84DD\u8272", color: "#3498db" },
      { name: "\u7EFF\u8272", color: "#2ecc71" },
      { name: "\u9EC4\u8272", color: "#f1c40f" },
      { name: "\u7D2B\u8272", color: "#9b59b6" },
      { name: "\u6A59\u8272", color: "#e67e22" }
    ];
    this.englishColors = [
      { name: "Red", color: "#e74c3c" },
      { name: "Blue", color: "#3498db" },
      { name: "Green", color: "#2ecc71" },
      { name: "Yellow", color: "#f1c40f" },
      { name: "Purple", color: "#9b59b6" },
      { name: "Orange", color: "#e67e22" }
    ];
    this.currentIndex = 0;
    this.timerInterval = null;
    this.startTime = 0;
    this.elapsedTime = 0;
    this.isRunning = false;
    this.records = [];
    this.targetColorSequence = [];
    this.targetTypeSequence = [];
    this.container = container;
    this.options = { language: "chinese", ...options };
    this.loadRecords("color-word-records");
    this.createUI();
    this.initGame();
    this.displayRecords();
  }
  get colors() {
    return this.options.language === "chinese" ? this.chineseColors : this.englishColors;
  }
  get questionTypes() {
    if (this.options.language === "chinese") {
      return [
        { id: "textColor", desc: "\u5B57\u4F53\u989C\u8272" },
        { id: "textContent", desc: "\u6587\u5B57\u5185\u5BB9" }
      ];
    } else {
      return [
        { id: "textColor", desc: "Text Color" },
        { id: "textContent", desc: "Text Content" }
      ];
    }
  }
  loadRecords(storageKey) {
    try {
      const savedRecords = localStorage.getItem(storageKey);
      if (savedRecords) {
        this.records = JSON.parse(savedRecords);
      }
    } catch (e) {
      console.error("Failed to load records:", e);
      this.records = [];
    }
  }
  saveRecords(storageKey) {
    try {
      localStorage.setItem(storageKey, JSON.stringify(this.records));
    } catch (e) {
      console.error("Failed to save records:", e);
    }
  }
  addRecord(time) {
    const gameTypeName = "\u989C\u8272\u5355\u8BCD";
    const newRecord = {
      date: Date.now(),
      time,
      size: this.options.rows * this.options.cols,
      type: "color-word",
      gameType: gameTypeName,
      metadata: `${this.options.rows}x${this.options.cols}`
    };
    this.records.unshift(newRecord);
    if (this.records.length > 10) {
      this.records = this.records.slice(0, 10);
    }
    this.saveRecords("color-word-records");
    this.displayRecords();
  }
  displayRecords() {
    if (!this.recordsContainer)
      return;
    this.recordsContainer.empty();
    const header = document.createElement("h3");
    header.setText("\u6700\u8FD1\u5B8C\u6210\u8BB0\u5F55");
    this.recordsContainer.appendChild(header);
    if (this.records.length === 0) {
      const noRecords = document.createElement("div");
      noRecords.setText("\u6682\u65E0\u8BB0\u5F55");
      noRecords.addClass("schulte-no-records");
      this.recordsContainer.appendChild(noRecords);
      return;
    }
    const recordsList = document.createElement("div");
    recordsList.addClass("schulte-records-list");
    const recordsToShow = this.records.slice(0, 5);
    recordsToShow.forEach((record, index) => {
      const recordItem = document.createElement("div");
      recordItem.addClass("schulte-record-item");
      const dateStr = new Date(record.date).toLocaleString();
      recordItem.innerHTML = `
        <span class="record-index">${index + 1}.</span>
        <span class="record-size">${record.metadata}</span>
        <span class="record-type">${record.gameType}</span>
        <span class="record-time">${record.time.toFixed(1)}\u79D2</span>
        <span class="record-date">${dateStr}</span>
      `;
      recordsList.appendChild(recordItem);
    });
    this.recordsContainer.appendChild(recordsList);
  }
  createUI() {
    const wrapper = document.createElement("div");
    wrapper.addClass("color-word-container");
    this.container.appendChild(wrapper);
    const languageSelector = document.createElement("div");
    languageSelector.addClass("language-selector");
    wrapper.appendChild(languageSelector);
    const languageLabel = document.createElement("span");
    languageLabel.setText("\u8BED\u8A00:");
    languageSelector.appendChild(languageLabel);
    const languageSelect = document.createElement("select");
    languageSelect.addClass("language-select");
    const chineseOption = document.createElement("option");
    chineseOption.value = "chinese";
    chineseOption.text = "\u4E2D\u6587";
    if (this.options.language === "chinese") {
      chineseOption.selected = true;
    }
    languageSelect.appendChild(chineseOption);
    const englishOption = document.createElement("option");
    englishOption.value = "english";
    englishOption.text = "English";
    if (this.options.language === "english") {
      englishOption.selected = true;
    }
    languageSelect.appendChild(englishOption);
    languageSelect.addEventListener("change", () => {
      this.options.language = languageSelect.value;
      this.resetGame();
      languageLabel.setText("\u8BED\u8A00:");
      this.startButton.setText("\u5F00\u59CB\u8BAD\u7EC3");
      this.resetButton.setText("\u91CD\u7F6E");
      this.updateStats("\u70B9\u51FB\u5F00\u59CB\u6309\u94AE\u5F00\u59CB\u8BAD\u7EC3");
    });
    languageSelector.appendChild(languageSelect);
    const controls = document.createElement("div");
    controls.addClass("game-controls");
    wrapper.appendChild(controls);
    this.startButton = document.createElement("button");
    this.startButton.setText("\u5F00\u59CB\u8BAD\u7EC3");
    this.startButton.addEventListener("click", () => this.startTraining());
    controls.appendChild(this.startButton);
    this.resetButton = document.createElement("button");
    this.resetButton.setText("\u91CD\u7F6E");
    this.resetButton.addEventListener("click", () => this.resetGame());
    controls.appendChild(this.resetButton);
    this.gameArea = document.createElement("div");
    this.gameArea.addClass("color-word-area");
    this.gameArea.style.setProperty("--grid-cols", this.options.cols.toString());
    this.gameArea.style.setProperty("--grid-rows", this.options.rows.toString());
    wrapper.appendChild(this.gameArea);
    if (this.options.showTimer) {
      this.timer = document.createElement("div");
      this.timer.addClass("game-timer");
      this.timer.setText("\u65F6\u95F4: 0.0\u79D2");
      wrapper.appendChild(this.timer);
    }
    this.stats = document.createElement("div");
    this.stats.addClass("game-stats");
    this.stats.setText("\u70B9\u51FB\u5F00\u59CB\u6309\u94AE\u5F00\u59CB\u8BAD\u7EC3");
    wrapper.appendChild(this.stats);
    this.recordsContainer = document.createElement("div");
    this.recordsContainer.addClass("game-records");
    wrapper.appendChild(this.recordsContainer);
  }
  initGame() {
    this.gameArea.empty();
    this.colorWordElements = [];
    this.generateColorWords();
    for (let i = 0; i < this.colorWords.length; i++) {
      const { word, color } = this.colorWords[i];
      const element = document.createElement("div");
      element.addClass("color-word");
      element.setText(word);
      element.style.color = color;
      element.addEventListener("click", () => this.handleWordClick(i));
      this.gameArea.appendChild(element);
      this.colorWordElements.push(element);
    }
  }
  generateColorWords() {
    const total = this.options.rows * this.options.cols;
    this.colorWords = [];
    for (let i = 0; i < this.colors.length; i++) {
      let wordIndex = i;
      let colorIndex = (i + 1) % this.colors.length;
      this.colorWords.push({
        word: this.colors[wordIndex].name,
        color: this.colors[colorIndex].color
      });
    }
    for (let i = 0; i < this.colors.length; i++) {
      let colorIndex = i;
      let wordIndex = (i + 1) % this.colors.length;
      const alreadyExists = this.colorWords.some((cw) => cw.word === this.colors[wordIndex].name && cw.color === this.colors[colorIndex].color);
      if (!alreadyExists) {
        this.colorWords.push({
          word: this.colors[wordIndex].name,
          color: this.colors[colorIndex].color
        });
      }
    }
    while (this.colorWords.length < total) {
      let wordIndex = Math.floor(Math.random() * this.colors.length);
      let colorIndex = Math.floor(Math.random() * this.colors.length);
      while (colorIndex === wordIndex) {
        colorIndex = Math.floor(Math.random() * this.colors.length);
      }
      this.colorWords.push({
        word: this.colors[wordIndex].name,
        color: this.colors[colorIndex].color
      });
    }
    if (this.colorWords.length > total) {
      this.colorWords = this.colorWords.slice(0, total);
    }
    this.shuffleColorWords();
    console.log("\u751F\u6210\u7684\u989C\u8272\u5355\u8BCD\uFF1A", this.colorWords);
    console.log("\u53EF\u7528\u7684\u989C\u8272\u5217\u8868\uFF1A", this.colors);
  }
  shuffleColorWords() {
    for (let i = this.colorWords.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [this.colorWords[i], this.colorWords[j]] = [this.colorWords[j], this.colorWords[i]];
    }
  }
  startTraining() {
    if (this.isRunning)
      return;
    this.isRunning = true;
    this.currentIndex = 0;
    this.startButton.setText("\u8BAD\u7EC3\u4E2D...");
    this.startButton.setAttribute("disabled", "true");
    this.colorWordElements.forEach((element) => {
      element.removeClass("correct");
      element.removeClass("wrong");
    });
    this.targetColorSequence = [...this.colors];
    this.shuffleArray(this.targetColorSequence);
    this.targetTypeSequence = [];
    const totalQuestions = this.targetColorSequence.length;
    for (let i = 0; i < totalQuestions; i++) {
      const questionType = this.questionTypes[Math.floor(Math.random() * this.questionTypes.length)].id;
      this.targetTypeSequence.push(questionType);
    }
    this.updateQuestionPrompt();
    this.startTime = Date.now();
    this.elapsedTime = 0;
    if (this.options.showTimer) {
      this.timerInterval = window.setInterval(() => {
        this.elapsedTime = (Date.now() - this.startTime) / 1e3;
        const timeText = `\u65F6\u95F4: ${this.elapsedTime.toFixed(1)}\u79D2`;
        this.timer.setText(timeText);
        if (this.options.timeLimit > 0 && this.elapsedTime >= this.options.timeLimit) {
          this.endTraining(false);
        }
      }, 100);
    }
  }
  updateQuestionPrompt() {
    const targetColor = this.targetColorSequence[this.currentIndex].name;
    const questionType = this.targetTypeSequence[this.currentIndex];
    if (this.options.language === "chinese") {
      if (questionType === "textColor") {
        this.updateStats(`\u8BF7\u70B9\u51FB\u3010${targetColor}\u3011\u5B57\u4F53\u989C\u8272\u7684\u5355\u8BCD`);
      } else {
        this.updateStats(`\u8BF7\u70B9\u51FB\u6587\u5B57\u5185\u5BB9\u662F\u3010${targetColor}\u3011\u7684\u5355\u8BCD`);
      }
    } else {
      if (questionType === "textColor") {
        this.updateStats(`Click word with \u3010${targetColor}\u3011 text color`);
      } else {
        this.updateStats(`Click word with text content \u3010${targetColor}\u3011`);
      }
    }
  }
  shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
  }
  handleWordClick(index) {
    if (!this.isRunning)
      return;
    const targetColor = this.targetColorSequence[this.currentIndex].name;
    const questionType = this.targetTypeSequence[this.currentIndex];
    const clickedWord = this.colorWords[index];
    const clickedTextColor = this.getColorNameByHex(clickedWord.color);
    const clickedTextContent = clickedWord.word;
    let isCorrect = false;
    if (questionType === "textColor") {
      isCorrect = clickedTextColor === targetColor;
    } else {
      isCorrect = clickedTextContent === targetColor;
    }
    if (isCorrect) {
      this.colorWordElements[index].addClass("correct");
      this.currentIndex++;
      if (this.currentIndex >= this.targetColorSequence.length) {
        this.endTraining(true);
        return;
      }
      this.updateQuestionPrompt();
    } else {
      this.colorWordElements[index].addClass("wrong");
      if (this.options.language === "chinese") {
        const questionTypeText = questionType === "textColor" ? "\u5B57\u4F53\u989C\u8272" : "\u6587\u5B57\u5185\u5BB9";
        this.updateStats(`\u9519\u8BEF! \u8BF7\u70B9\u51FB\u3010${targetColor}\u3011${questionTypeText}\u7684\u5355\u8BCD`);
      } else {
        const questionTypeText = questionType === "textColor" ? "text color" : "text content";
        this.updateStats(`Wrong! Click word with \u3010${targetColor}\u3011 ${questionTypeText}`);
      }
      setTimeout(() => {
        this.colorWordElements[index].removeClass("wrong");
      }, 500);
    }
  }
  endTraining(success) {
    this.isRunning = false;
    if (this.timerInterval) {
      clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
    this.startButton.setText("\u5F00\u59CB\u8BAD\u7EC3");
    this.startButton.removeAttribute("disabled");
    if (success) {
      const successText = `\u8BAD\u7EC3\u5B8C\u6210! \u7528\u65F6: ${this.elapsedTime.toFixed(1)}\u79D2`;
      this.updateStats(successText);
      this.addRecord(this.elapsedTime);
    } else {
      const timeoutText = `\u65F6\u95F4\u5230! \u5B8C\u6210\u5EA6: ${this.currentIndex}/${this.targetColorSequence.length}`;
      this.updateStats(timeoutText);
    }
  }
  resetGame() {
    if (this.isRunning) {
      this.endTraining(false);
    }
    this.initGame();
    this.currentIndex = 0;
    this.elapsedTime = 0;
    if (this.options.showTimer) {
      const timerText = "\u65F6\u95F4: 0.0\u79D2";
      this.timer.setText(timerText);
    }
    const startText = "\u70B9\u51FB\u5F00\u59CB\u6309\u94AE\u5F00\u59CB\u8BAD\u7EC3";
    this.updateStats(startText);
  }
  updateStats(text) {
    this.stats.setText(text);
  }
  getColorNameByHex(hexColor) {
    const matchedColor = this.colors.find((c) => c.color === hexColor);
    return matchedColor ? matchedColor.name : "";
  }
};

// src/types.ts
var import_obsidian = __toModule(require("obsidian"));

// src/main.ts
var DEFAULT_SETTINGS = {
  defaultSize: 5,
  defaultType: "numbers",
  defaultTimeLimit: 60,
  showTimer: true,
  defaultGame: "schulte-table",
  colorWordRows: 4,
  colorWordCols: 4
};
var VIEW_TYPE_SCHULTE = "schulte-table-view";
var SchulteTableSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.schulteTableContainer = null;
    this.colorWordContainer = null;
    this.plugin = plugin;
    this.currentGame = this.plugin.settings.defaultGame;
  }
  getViewType() {
    return VIEW_TYPE_SCHULTE;
  }
  getDisplayText() {
    return "\u6CE8\u610F\u529B\u8BAD\u7EC3";
  }
  getIcon() {
    return "target";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("schulte-table-sidebar-view");
    const gameSelector = container.createEl("div");
    gameSelector.addClass("game-selector");
    const selectContainer = gameSelector.createEl("div");
    selectContainer.addClass("select-container");
    const selectLabel = selectContainer.createEl("span");
    selectLabel.addClass("select-label");
    selectLabel.setText("\u6E38\u620F:");
    const gameSelect = selectContainer.createEl("select");
    gameSelect.addClass("game-select");
    const games = [
      { value: "schulte-table", text: "\u8212\u5C14\u7279\u8868\u683C" },
      { value: "color-word", text: "\u989C\u8272\u5355\u8BCD" }
    ];
    games.forEach((game) => {
      const option = document.createElement("option");
      option.value = game.value;
      option.text = game.text;
      if (game.value === this.currentGame) {
        option.selected = true;
      }
      gameSelect.appendChild(option);
    });
    gameSelect.addEventListener("change", () => {
      this.switchGame(gameSelect.value);
    });
    const controlPanel = container.createEl("div");
    controlPanel.addClass("schulte-control-panel");
    if (this.currentGame === "schulte-table") {
      this.addSchulteTableControls(controlPanel);
    } else if (this.currentGame === "color-word") {
      this.addColorWordControls(controlPanel);
    }
    this.gameContainer = container.createEl("div");
    this.gameContainer.addClass("game-container");
    this.initCurrentGame();
  }
  addSchulteTableControls(container) {
    const sizeSelector = container.createEl("div");
    sizeSelector.addClass("schulte-size-selector");
    const sizeLabel = sizeSelector.createEl("span");
    sizeLabel.setText("\u5927\u5C0F:");
    const sizeSelect = sizeSelector.createEl("select");
    [3, 4, 5, 6, 7].forEach((size) => {
      const option = document.createElement("option");
      option.value = size.toString();
      option.text = `${size}\xD7${size}`;
      if (size === this.plugin.settings.defaultSize) {
        option.selected = true;
      }
      sizeSelect.appendChild(option);
    });
    const typeSelector = container.createEl("div");
    typeSelector.addClass("schulte-type-selector");
    const typeLabel = typeSelector.createEl("span");
    typeLabel.setText("\u7C7B\u578B:");
    const typeSelect = typeSelector.createEl("select");
    [
      { value: "numbers", text: "\u6570\u5B57" },
      { value: "letters", text: "\u5B57\u6BCD" },
      { value: "chinese", text: "\u6C49\u5B57" }
    ].forEach((type) => {
      const option = document.createElement("option");
      option.value = type.value;
      option.text = type.text;
      if (type.value === this.plugin.settings.defaultType) {
        option.selected = true;
      }
      typeSelect.appendChild(option);
    });
    sizeSelect.addEventListener("change", () => {
      const newSize = parseInt(sizeSelect.value);
      this.plugin.settings.defaultSize = newSize;
      this.plugin.saveSettings().then(() => {
        this.refreshSchulteTable();
      });
    });
    typeSelect.addEventListener("change", () => {
      const newType = typeSelect.value;
      this.plugin.settings.defaultType = newType;
      this.plugin.saveSettings().then(() => {
        this.refreshSchulteTable();
      });
    });
  }
  addColorWordControls(container) {
    const rowSelector = container.createEl("div");
    rowSelector.addClass("color-word-row-selector");
    const rowLabel = rowSelector.createEl("span");
    rowLabel.setText("\u884C\u6570:");
    const rowSelect = rowSelector.createEl("select");
    [2, 3, 4, 5, 6].forEach((rows) => {
      const option = document.createElement("option");
      option.value = rows.toString();
      option.text = `${rows}\u884C`;
      if (rows === this.plugin.settings.colorWordRows) {
        option.selected = true;
      }
      rowSelect.appendChild(option);
    });
    const colSelector = container.createEl("div");
    colSelector.addClass("color-word-col-selector");
    const colLabel = colSelector.createEl("span");
    colLabel.setText("\u5217\u6570:");
    const colSelect = colSelector.createEl("select");
    [2, 3, 4, 5, 6].forEach((cols) => {
      const option = document.createElement("option");
      option.value = cols.toString();
      option.text = `${cols}\u5217`;
      if (cols === this.plugin.settings.colorWordCols) {
        option.selected = true;
      }
      colSelect.appendChild(option);
    });
    rowSelect.addEventListener("change", () => {
      const newRows = parseInt(rowSelect.value);
      this.plugin.settings.colorWordRows = newRows;
      this.plugin.saveSettings().then(() => {
        this.refreshColorWordGame();
      });
    });
    colSelect.addEventListener("change", () => {
      const newCols = parseInt(colSelect.value);
      this.plugin.settings.colorWordCols = newCols;
      this.plugin.saveSettings().then(() => {
        this.refreshColorWordGame();
      });
    });
  }
  switchGame(gameType) {
    this.currentGame = gameType;
    this.plugin.settings.defaultGame = gameType;
    this.plugin.saveSettings().then(() => {
      this.onOpen();
    });
  }
  initCurrentGame() {
    if (this.currentGame === "schulte-table") {
      this.initSchulteTable();
    } else if (this.currentGame === "color-word") {
      this.initColorWordGame();
    }
  }
  initSchulteTable() {
    this.schulteTableContainer = this.gameContainer.createEl("div");
    new SchulteTableView(this.schulteTableContainer, {
      size: this.plugin.settings.defaultSize,
      type: this.plugin.settings.defaultType,
      timeLimit: this.plugin.settings.defaultTimeLimit,
      showTimer: this.plugin.settings.showTimer
    });
  }
  initColorWordGame() {
    this.colorWordContainer = this.gameContainer.createEl("div");
    new ColorWordView(this.colorWordContainer, {
      rows: this.plugin.settings.colorWordRows,
      cols: this.plugin.settings.colorWordCols,
      timeLimit: this.plugin.settings.defaultTimeLimit,
      showTimer: this.plugin.settings.showTimer
    });
  }
  refreshSchulteTable() {
    if (this.schulteTableContainer) {
      this.schulteTableContainer.empty();
      new SchulteTableView(this.schulteTableContainer, {
        size: this.plugin.settings.defaultSize,
        type: this.plugin.settings.defaultType,
        timeLimit: this.plugin.settings.defaultTimeLimit,
        showTimer: this.plugin.settings.showTimer
      });
    }
  }
  refreshColorWordGame() {
    if (this.colorWordContainer) {
      this.colorWordContainer.empty();
      new ColorWordView(this.colorWordContainer, {
        rows: this.plugin.settings.colorWordRows,
        cols: this.plugin.settings.colorWordCols,
        timeLimit: this.plugin.settings.defaultTimeLimit,
        showTimer: this.plugin.settings.showTimer
      });
    }
  }
  async onClose() {
    this.gameContainer.empty();
  }
};
var SchulteTablePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SchulteTableSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_SCHULTE, (leaf) => new SchulteTableSidebarView(leaf, this));
    this.addCommand({
      id: "open-schulte-table-view",
      name: "\u6253\u5F00\u6CE8\u610F\u529B\u8BAD\u7EC3\u89C6\u56FE",
      callback: () => {
        this.activateView();
      }
    });
    this.registerMarkdownCodeBlockProcessor("schulte-table", (source, el, ctx) => {
      this.processSchulteTable(source, el, ctx);
    });
    this.addCommand({
      id: "insert-schulte-table",
      name: "\u63D2\u5165\u8212\u5C14\u7279\u8868\u683C",
      editorCallback: (editor) => {
        const size = this.settings.defaultSize;
        const type = this.settings.defaultType;
        const timeLimit = this.settings.defaultTimeLimit;
        const codeBlock = `\`\`\`schulte-table
size: ${size}
type: ${type}
timeLimit: ${timeLimit}
\`\`\``;
        editor.replaceSelection(codeBlock);
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_SCHULTE);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_SCHULTE);
    if (existing.length) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false) || this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_SCHULTE,
      active: true
    });
  }
  processSchulteTable(source, el, ctx) {
    const params = this.parseParams(source);
    const size = parseInt(params.size) || this.settings.defaultSize;
    const type = params.type || this.settings.defaultType;
    const timeLimit = parseInt(params.timeLimit) || this.settings.defaultTimeLimit;
    new SchulteTableView(el, {
      size,
      type,
      timeLimit,
      showTimer: this.settings.showTimer
    });
  }
  parseParams(source) {
    const params = {};
    const lines = source.split("\n");
    for (const line of lines) {
      const parts = line.split(":");
      if (parts.length >= 2) {
        const key = parts[0].trim();
        const value = parts.slice(1).join(":").trim();
        params[key] = value;
      }
    }
    return params;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SchulteTableSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u6CE8\u610F\u529B\u8BAD\u7EC3\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u6E38\u620F\u7C7B\u578B").setDesc("\u8BBE\u7F6E\u9ED8\u8BA4\u7684\u6CE8\u610F\u529B\u8BAD\u7EC3\u6E38\u620F\u7C7B\u578B").addDropdown((dropdown) => {
      dropdown.addOption("schulte-table", "\u8212\u5C14\u7279\u8868\u683C").addOption("color-word", "\u989C\u8272\u5355\u8BCD").setValue(this.plugin.settings.defaultGame).onChange(async (value) => {
        this.plugin.settings.defaultGame = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "\u8212\u5C14\u7279\u8868\u683C\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u8868\u683C\u5927\u5C0F").setDesc("\u8BBE\u7F6E\u8212\u5C14\u7279\u8868\u683C\u7684\u9ED8\u8BA4\u5927\u5C0F\uFF08\u59825\u8868\u793A5x5\u8868\u683C\uFF09").addDropdown((dropdown) => {
      dropdown.addOption("3", "3x3").addOption("4", "4x4").addOption("5", "5x5").addOption("6", "6x6").addOption("7", "7x7").setValue(this.plugin.settings.defaultSize.toString()).onChange(async (value) => {
        this.plugin.settings.defaultSize = parseInt(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u8868\u683C\u7C7B\u578B").setDesc("\u8BBE\u7F6E\u8212\u5C14\u7279\u8868\u683C\u7684\u9ED8\u8BA4\u5185\u5BB9\u7C7B\u578B").addDropdown((dropdown) => {
      dropdown.addOption("numbers", "\u6570\u5B57").addOption("letters", "\u5B57\u6BCD").addOption("chinese", "\u6C49\u5B57").setValue(this.plugin.settings.defaultType).onChange(async (value) => {
        this.plugin.settings.defaultType = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "\u989C\u8272\u5355\u8BCD\u6E38\u620F\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u884C\u6570").setDesc("\u8BBE\u7F6E\u989C\u8272\u5355\u8BCD\u6E38\u620F\u7684\u9ED8\u8BA4\u884C\u6570").addDropdown((dropdown) => {
      dropdown.addOption("2", "2\u884C").addOption("3", "3\u884C").addOption("4", "4\u884C").addOption("5", "5\u884C").addOption("6", "6\u884C").setValue(this.plugin.settings.colorWordRows.toString()).onChange(async (value) => {
        this.plugin.settings.colorWordRows = parseInt(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u5217\u6570").setDesc("\u8BBE\u7F6E\u989C\u8272\u5355\u8BCD\u6E38\u620F\u7684\u9ED8\u8BA4\u5217\u6570").addDropdown((dropdown) => {
      dropdown.addOption("2", "2\u5217").addOption("3", "3\u5217").addOption("4", "4\u5217").addOption("5", "5\u5217").addOption("6", "6\u5217").setValue(this.plugin.settings.colorWordCols.toString()).onChange(async (value) => {
        this.plugin.settings.colorWordCols = parseInt(value);
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "\u901A\u7528\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u9ED8\u8BA4\u65F6\u95F4\u9650\u5236\uFF08\u79D2\uFF09").setDesc("\u8BBE\u7F6E\u8BAD\u7EC3\u7684\u9ED8\u8BA4\u65F6\u95F4\u9650\u5236").addText((text) => text.setValue(this.plugin.settings.defaultTimeLimit.toString()).onChange(async (value) => {
      const timeLimit = parseInt(value);
      if (!isNaN(timeLimit) && timeLimit > 0) {
        this.plugin.settings.defaultTimeLimit = timeLimit;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian2.Setting(containerEl).setName("\u663E\u793A\u8BA1\u65F6\u5668").setDesc("\u662F\u5426\u663E\u793A\u8BAD\u7EC3\u7684\u8BA1\u65F6\u5668").addToggle((toggle) => toggle.setValue(this.plugin.settings.showTimer).onChange(async (value) => {
      this.plugin.settings.showTimer = value;
      await this.plugin.saveSettings();
    }));
  }
};
